create table T_PRODUCT
(
	ID VARCHAR2(64) not null
		primary key,
	NAME VARCHAR2(255) not null,
	TYPE CHAR(4) not null,
	CREATE_TIME DATE not null,
	UPDATE_TIME DATE not null,
	PRICE NUMBER(10,2) not null,
	"desc" VARCHAR2(4000)
)
/

create index T_PRODUCT_NAME_INDEX
	on T_PRODUCT (NAME)
/

create table T_OPERATE_LOG
(
	ID VARCHAR2(64) not null
		primary key,
	OPERATE_TABLE VARCHAR2(255) not null,
	OPERATE_TYPE VARCHAR2(50) not null,
	OPERATE_STATUS CHAR not null,
	CREATE_TIME DATE not null,
	UPDATE_TIME DATE not null,
	OPERATE_CUSTOMER VARCHAR2(64) not null,
	DATA_ID VARCHAR2(64)
)
/

create table T_USER_INFO
(
	ID VARCHAR2(64) not null
		constraint T_USER_INFO_PK
			primary key,
	USER_NAME VARCHAR2(255) not null,
	PHONE NUMBER,
	EMAIL VARCHAR2(255),
	CARD_NUMBER NUMBER,
	ROLE VARCHAR2(32),
	SEX NUMBER,
	HEIGHT NUMBER,
	WEIGHT NUMBER(10,2),
	COMPANY VARCHAR2(255),
	IS_MARRIED VARCHAR2(4),
	IS_GRADUATED VARCHAR2(4),
	WORK_EXPERIENCE VARCHAR2(32),
	GRADUATE_SCHOOL VARCHAR2(255),
	ADDRESS VARCHAR2(255)
)
/

